image: python:3.6

stages:
  - tests
  - deploy

cache:
  key: pip
  paths:
    - .pip

before_script:
  - mkdir -p .pip
  - pip install -U pip
  - pip --cache-dir=.pip --quiet install tox twine

py36:
  stage: tests
  image: python:3.6
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'
  script: 
    - tox
    
pypi:
  stage: deploy
#   only:
#     - /^(\d+\.\d+)$/
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - echo $TWINE_USERNAME
    - python setup.py -q sdist bdist_wheel
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
