image: python:3.6

stages:
  - tests
  - deploy

cache:
  key: pip
  paths:
    - .pip

before_script:
  - mkdir -p .pip
  - pip install -U pip
  - pip --cache-dir=.pip install tox

py36:
  stage: tests
  image: python:3.6
  script: 
    - tox
    
pypi:
  stage: deploy
  only:
    - /^(\d+\.\d+)$/
  variables:
    PIPY_USER: $PIPY_USER
    PIPY_PSW: $PIPY_PSW
  script:
    - echo "Deploy to pypi" # python setup.py sdist bdist_wheel
